# MariaDB/MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/course_work?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

# Логирование
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=INFO
spring.security.user.name=user
spring.security.user.password=user
spring.security.enabled=false
upload.path=D:/coursovoi proekt/vinyl/vinyl-backend/uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Discogs API Configuration
discogs.user-token=UAKCwWSeAJSQvZVlTUGOZyhggiiCsbxBJbAFxqcl
discogs.user-agent=VinylStoreApp/1.0
# MySQL/MariaDB Configuration - используем course_work
# Логирование SQL
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
youtube.api-key=ВАШ_API_КЛЮЧ
spring.web.cors.allowed-origins=http://localhost:5173
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true
# Кодировка для поддержки кириллицы
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true
spring.web.locale=ru_RU
# Yandex.Music API Configuration
yandex.music.token=y0__wgBENe93IAHGN74BiDBr_nZF36U18eoxGtK-PIRC08QlbjPF3sP
yandex.music.base.url=https://api.music.yandex.net